### GET to / Zulu
GET localhost:8080/

### POST to / Eastern Time
POST localhost:8080/
content-type: application/json

{
  "tz": "America/New_York"
}

### POST to / Pacific Standard Time
POST localhost:8080/
content-type: application/json

{
  "tz": "PST"
}
